[2023-09-27T17:31:44.283+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_scraping_dag.see_containers manual__2023-09-27T17:30:25.743319+00:00 [queued]>
[2023-09-27T17:31:44.345+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_scraping_dag.see_containers manual__2023-09-27T17:30:25.743319+00:00 [queued]>
[2023-09-27T17:31:44.346+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-09-27T17:31:44.414+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): see_containers> on 2023-09-27 17:30:25.743319+00:00
[2023-09-27T17:31:44.434+0000] {standard_task_runner.py:57} INFO - Started process 141 to run task
[2023-09-27T17:31:44.442+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'web_scraping_dag', 'see_containers', 'manual__2023-09-27T17:30:25.743319+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/web_scrapping_test.py', '--cfg-path', '/tmp/tmpji1nl6w1']
[2023-09-27T17:31:44.453+0000] {standard_task_runner.py:85} INFO - Job 301: Subtask see_containers
[2023-09-27T17:31:44.653+0000] {task_command.py:410} INFO - Running <TaskInstance: web_scraping_dag.see_containers manual__2023-09-27T17:30:25.743319+00:00 [running]> on host a9130fa7679f
[2023-09-27T17:31:45.187+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_scraping_dag' AIRFLOW_CTX_TASK_ID='see_containers' AIRFLOW_CTX_EXECUTION_DATE='2023-09-27T17:30:25.743319+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-27T17:30:25.743319+00:00'
[2023-09-27T17:31:45.190+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-09-27T17:31:45.200+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker ps']
[2023-09-27T17:31:45.259+0000] {subprocess.py:86} INFO - Output:
[2023-09-27T17:31:45.493+0000] {subprocess.py:93} INFO - Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json": dial unix /var/run/docker.sock: connect: permission denied
[2023-09-27T17:31:45.561+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-09-27T17:31:45.714+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-09-27T17:31:45.784+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=web_scraping_dag, task_id=see_containers, execution_date=20230927T173025, start_date=20230927T173144, end_date=20230927T173145
[2023-09-27T17:31:46.857+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 301 for task see_containers (Bash command failed. The command returned a non-zero exit code 1.; 141)
[2023-09-27T17:31:46.987+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-09-27T17:31:47.645+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
